/**
 * This file defines the Schema for the user model to save in the database. Note that the user ID key is automatically generated by MonbgoDB
 */

var mongoose = require('mongoose');
mongoose.Promise = global.Promise;

var user = mongoose.model('user', { first_name: String,
    last_name: String,
    password: String,
    email: String,
    friend_list: [String]
    });
    
user.create_friendship = function(this_user_id, new_friend_id){
    user.findByIdAndUpdate(
        this_user_id,
        {$push: {"friend_list": new_friend_id}},
        {safe: true, upsert: true},
        function(err, model) {
            console.log(err);
        }
    );
        user.findByIdAndUpdate(
        new_friend_id,
        {$push: {"friend_list": this_user_id}},
        {safe: true, upsert: true},
        function(err, model) {
            console.log(err);
        }
    );
}
module.exports = user;